//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp111
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Windows.Forms;

    
    public partial class NodeManagerDBEntities : DbContext
    {
        public NodeManagerDBEntities()
            : base("name=NodeManagerDBEntities")
        {
            //var f = new Form1();
            //f.Show();
            Console.WriteLine("Enter password");
            Database.Connection.ConnectionString = Database.Connection.ConnectionString.Replace("XXXXX", Console.ReadLine());
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FamilySymbol> FamilySymbols { get; set; }
        public virtual DbSet<Node> Nodes { get; set; }
        public virtual DbSet<RevitParameter> RevitParameters { get; set; }
    }
}
